// <auto-generated />
using System;
using AzureGettingStarted.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AzureGettingStarted.API.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AzureGettingStarted.Model.Adult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AdultScore")
                        .HasColumnType("float");

                    b.Property<bool>("IsAdultContent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRacyContent")
                        .HasColumnType("bit");

                    b.Property<double>("RacyScore")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Adult");
                });

            modelBuilder.Entity("AzureGettingStarted.Model.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Confidence")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RectangleId")
                        .HasColumnType("int");

                    b.Property<int?>("VisionResultId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RectangleId");

                    b.HasIndex("VisionResultId");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("AzureGettingStarted.Model.Caption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Confidence")
                        .HasColumnType("float");

                    b.Property<int?>("DescriptionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId");

                    b.ToTable("Caption");
                });

            modelBuilder.Entity("AzureGettingStarted.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<int?>("VisionResultId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VisionResultId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("AzureGettingStarted.Model.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccentColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DominantColorBackground")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DominantColorForeground")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBwImg")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Color");
                });

            modelBuilder.Entity("AzureGettingStarted.Model.Description", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Description");
                });

            modelBuilder.Entity("AzureGettingStarted.Model.Face", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("FaceRectangleId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VisionResultId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FaceRectangleId");

                    b.HasIndex("VisionResultId");

                    b.ToTable("Face");
                });

            modelBuilder.Entity("AzureGettingStarted.Model.FaceRectangle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("Left")
                        .HasColumnType("float");

                    b.Property<double>("Top")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("FaceRectangle");
                });

            modelBuilder.Entity("AzureGettingStarted.Model.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VisionResultId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VisionResultId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("AzureGettingStarted.Model.ImageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClipArtType")
                        .HasColumnType("int");

                    b.Property<int>("LineDrawingType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ImageType");
                });

            modelBuilder.Entity("AzureGettingStarted.Model.Metadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Metadata");
                });

            modelBuilder.Entity("AzureGettingStarted.Model.Rectangle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("H")
                        .HasColumnType("int");

                    b.Property<int>("W")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rectangle");
                });

            modelBuilder.Entity("AzureGettingStarted.Model.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Confidence")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VisionResultId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VisionResultId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("AzureGettingStarted.Model.Thing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Confidence")
                        .HasColumnType("float");

                    b.Property<string>("Object")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RectangleId")
                        .HasColumnType("int");

                    b.Property<int?>("VisionResultId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RectangleId");

                    b.HasIndex("VisionResultId");

                    b.ToTable("Thing");
                });

            modelBuilder.Entity("AzureGettingStarted.Model.VisionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdultId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<int?>("DescriptionId")
                        .HasColumnType("int");

                    b.Property<int?>("ImageTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("MetadataId")
                        .HasColumnType("int");

                    b.Property<string>("RequestId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdultId");

                    b.HasIndex("ColorId");

                    b.HasIndex("DescriptionId");

                    b.HasIndex("ImageTypeId");

                    b.HasIndex("MetadataId");

                    b.ToTable("VisionResult");
                });

            modelBuilder.Entity("AzureGettingStarted.Model.Brand", b =>
                {
                    b.HasOne("AzureGettingStarted.Model.Rectangle", "Rectangle")
                        .WithMany()
                        .HasForeignKey("RectangleId");

                    b.HasOne("AzureGettingStarted.Model.VisionResult", null)
                        .WithMany("Brands")
                        .HasForeignKey("VisionResultId");
                });

            modelBuilder.Entity("AzureGettingStarted.Model.Caption", b =>
                {
                    b.HasOne("AzureGettingStarted.Model.Description", null)
                        .WithMany("Captions")
                        .HasForeignKey("DescriptionId");
                });

            modelBuilder.Entity("AzureGettingStarted.Model.Category", b =>
                {
                    b.HasOne("AzureGettingStarted.Model.VisionResult", null)
                        .WithMany("Categories")
                        .HasForeignKey("VisionResultId");
                });

            modelBuilder.Entity("AzureGettingStarted.Model.Face", b =>
                {
                    b.HasOne("AzureGettingStarted.Model.FaceRectangle", "FaceRectangle")
                        .WithMany()
                        .HasForeignKey("FaceRectangleId");

                    b.HasOne("AzureGettingStarted.Model.VisionResult", null)
                        .WithMany("Faces")
                        .HasForeignKey("VisionResultId");
                });

            modelBuilder.Entity("AzureGettingStarted.Model.Image", b =>
                {
                    b.HasOne("AzureGettingStarted.Model.VisionResult", "VisionResult")
                        .WithMany()
                        .HasForeignKey("VisionResultId");
                });

            modelBuilder.Entity("AzureGettingStarted.Model.Tag", b =>
                {
                    b.HasOne("AzureGettingStarted.Model.VisionResult", null)
                        .WithMany("Tags")
                        .HasForeignKey("VisionResultId");
                });

            modelBuilder.Entity("AzureGettingStarted.Model.Thing", b =>
                {
                    b.HasOne("AzureGettingStarted.Model.Rectangle", "Rectangle")
                        .WithMany()
                        .HasForeignKey("RectangleId");

                    b.HasOne("AzureGettingStarted.Model.VisionResult", null)
                        .WithMany("Objects")
                        .HasForeignKey("VisionResultId");
                });

            modelBuilder.Entity("AzureGettingStarted.Model.VisionResult", b =>
                {
                    b.HasOne("AzureGettingStarted.Model.Adult", "Adult")
                        .WithMany()
                        .HasForeignKey("AdultId");

                    b.HasOne("AzureGettingStarted.Model.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId");

                    b.HasOne("AzureGettingStarted.Model.Description", "Description")
                        .WithMany()
                        .HasForeignKey("DescriptionId");

                    b.HasOne("AzureGettingStarted.Model.ImageType", "ImageType")
                        .WithMany()
                        .HasForeignKey("ImageTypeId");

                    b.HasOne("AzureGettingStarted.Model.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");
                });
#pragma warning restore 612, 618
        }
    }
}
